// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	entity "git.garena.com/sea-labs-id/bootcamp/batch-03/frederik-hutabarat/exercise-library-api/entity"
	mock "github.com/stretchr/testify/mock"
)

// AuthorRepository is an autogenerated mock type for the AuthorRepository type
type AuthorRepository struct {
	mock.Mock
}

// FindOneById provides a mock function with given fields: id
func (_m *AuthorRepository) FindOneById(id int64) (*entity.Author, error) {
	ret := _m.Called(id)

	var r0 *entity.Author
	if rf, ok := ret.Get(0).(func(int64) *entity.Author); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
