// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/frederikdaniel7/go-gin-library-api/entity"
	mock "github.com/stretchr/testify/mock"
)

// AuthorRepository is an autogenerated mock type for the AuthorRepository type
type AuthorRepository struct {
	mock.Mock
}

// FindOneById provides a mock function with given fields: ctx, id
func (_m *AuthorRepository) FindOneById(ctx context.Context, id int64) (*entity.Author, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.Author
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.Author); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Author)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
