// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/frederikdaniel7/go-gin-library-api/dto"
	mock "github.com/stretchr/testify/mock"
)

// BorrowRecordUseCase is an autogenerated mock type for the BorrowRecordUseCase type
type BorrowRecordUseCase struct {
	mock.Mock
}

// NewBorrowRecord provides a mock function with given fields: ctx, body
func (_m *BorrowRecordUseCase) NewBorrowRecord(ctx context.Context, body dto.CreateBorrowRecordBody) (*dto.BorrowRecord, error) {
	ret := _m.Called(ctx, body)

	var r0 *dto.BorrowRecord
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateBorrowRecordBody) *dto.BorrowRecord); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BorrowRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateBorrowRecordBody) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReturnBorrowedBook provides a mock function with given fields: ctx, id
func (_m *BorrowRecordUseCase) ReturnBorrowedBook(ctx context.Context, id int) (*dto.BorrowRecord, error) {
	ret := _m.Called(ctx, id)

	var r0 *dto.BorrowRecord
	if rf, ok := ret.Get(0).(func(context.Context, int) *dto.BorrowRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.BorrowRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
