// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/frederikdaniel7/go-gin-library-api/dto"
	entity "github.com/frederikdaniel7/go-gin-library-api/entity"

	mock "github.com/stretchr/testify/mock"
)

// BorrowRecordRepository is an autogenerated mock type for the BorrowRecordRepository type
type BorrowRecordRepository struct {
	mock.Mock
}

// CreateBorrowRecord provides a mock function with given fields: ctx, body
func (_m *BorrowRecordRepository) CreateBorrowRecord(ctx context.Context, body dto.CreateBorrowRecordBody) (*entity.BorrowRecord, error) {
	ret := _m.Called(ctx, body)

	var r0 *entity.BorrowRecord
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateBorrowRecordBody) *entity.BorrowRecord); ok {
		r0 = rf(ctx, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BorrowRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateBorrowRecordBody) error); ok {
		r1 = rf(ctx, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneById provides a mock function with given fields: ctx, id
func (_m *BorrowRecordRepository) FindOneById(ctx context.Context, id int64) (*entity.BorrowRecord, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.BorrowRecord
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.BorrowRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BorrowRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecordReturnBook provides a mock function with given fields: ctx, id
func (_m *BorrowRecordRepository) UpdateRecordReturnBook(ctx context.Context, id int64) (*entity.BorrowRecord, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.BorrowRecord
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.BorrowRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.BorrowRecord)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
